"""initialisation tebles

Revision ID: c9ad6d7d2ea9
Revises: 
Create Date: 2022-12-15 18:12:14.112478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ad6d7d2ea9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annee_scolaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annee_scolaire_name'), 'annee_scolaire', ['name'], unique=False)
    op.create_table('date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=64), nullable=True),
    sa.Column('date_deb1', sa.DateTime(), nullable=True),
    sa.Column('date_fin1', sa.DateTime(), nullable=True),
    sa.Column('date_deb2', sa.DateTime(), nullable=True),
    sa.Column('date_fin2', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_date_annee_scolaire'), 'date', ['annee_scolaire'], unique=False)
    op.create_table('entreprise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('adresse1', sa.String(length=64), nullable=True),
    sa.Column('adresse2', sa.String(length=64), nullable=True),
    sa.Column('CP', sa.String(length=5), nullable=True),
    sa.Column('ville', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('phonenumber', sa.String(length=10), nullable=True),
    sa.Column('mail', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entreprise_CP'), 'entreprise', ['CP'], unique=False)
    op.create_index(op.f('ix_entreprise_active'), 'entreprise', ['active'], unique=False)
    op.create_index(op.f('ix_entreprise_adresse1'), 'entreprise', ['adresse1'], unique=False)
    op.create_index(op.f('ix_entreprise_adresse2'), 'entreprise', ['adresse2'], unique=False)
    op.create_index(op.f('ix_entreprise_mail'), 'entreprise', ['mail'], unique=False)
    op.create_index(op.f('ix_entreprise_name'), 'entreprise', ['name'], unique=False)
    op.create_index(op.f('ix_entreprise_phonenumber'), 'entreprise', ['phonenumber'], unique=False)
    op.create_index(op.f('ix_entreprise_ville'), 'entreprise', ['ville'], unique=False)
    op.create_table('groupe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groupe_name'), 'groupe', ['name'], unique=False)
    op.create_table('niveau',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_niveau_name'), 'niveau', ['name'], unique=False)
    op.create_table('professeur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('annee_deb', sa.Integer(), nullable=True),
    sa.Column('annee_fin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_name'), 'promotion', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('classe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('niveau_id', sa.Integer(), nullable=True),
    sa.Column('annee_scolaire_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaire.id'], ),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveau.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classe_name'), 'classe', ['name'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('fonction', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('phonenumber1', sa.String(length=10), nullable=True),
    sa.Column('phonenumber2', sa.String(length=10), nullable=True),
    sa.Column('mail', sa.String(length=64), nullable=True),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_active'), 'contact', ['active'], unique=False)
    op.create_index(op.f('ix_contact_firstname'), 'contact', ['firstname'], unique=False)
    op.create_index(op.f('ix_contact_fonction'), 'contact', ['fonction'], unique=False)
    op.create_index(op.f('ix_contact_mail'), 'contact', ['mail'], unique=False)
    op.create_index(op.f('ix_contact_name'), 'contact', ['name'], unique=False)
    op.create_index(op.f('ix_contact_phonenumber1'), 'contact', ['phonenumber1'], unique=False)
    op.create_index(op.f('ix_contact_phonenumber2'), 'contact', ['phonenumber2'], unique=False)
    op.create_table('eleve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('phonenumber', sa.String(length=10), nullable=True),
    sa.Column('mail1', sa.String(length=64), nullable=True),
    sa.Column('mail2', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eleve_active'), 'eleve', ['active'], unique=False)
    op.create_index(op.f('ix_eleve_firstname'), 'eleve', ['firstname'], unique=False)
    op.create_index(op.f('ix_eleve_mail1'), 'eleve', ['mail1'], unique=False)
    op.create_index(op.f('ix_eleve_mail2'), 'eleve', ['mail2'], unique=False)
    op.create_index(op.f('ix_eleve_name'), 'eleve', ['name'], unique=False)
    op.create_index(op.f('ix_eleve_phonenumber'), 'eleve', ['phonenumber'], unique=False)
    op.create_table('eleve_classe',
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.Column('eleve_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleve.id'], )
    )
    op.create_table('prof_classes',
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.Column('prof_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], ),
    sa.ForeignKeyConstraint(['prof_id'], ['professeur.id'], )
    )
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=True),
    sa.Column('niveau_id', sa.Integer(), nullable=True),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('periode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleve.id'], ),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['niveau_id'], ['niveau.id'], ),
    sa.ForeignKeyConstraint(['periode_id'], ['date.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage')
    op.drop_table('prof_classes')
    op.drop_table('eleve_classe')
    op.drop_index(op.f('ix_eleve_phonenumber'), table_name='eleve')
    op.drop_index(op.f('ix_eleve_name'), table_name='eleve')
    op.drop_index(op.f('ix_eleve_mail2'), table_name='eleve')
    op.drop_index(op.f('ix_eleve_mail1'), table_name='eleve')
    op.drop_index(op.f('ix_eleve_firstname'), table_name='eleve')
    op.drop_index(op.f('ix_eleve_active'), table_name='eleve')
    op.drop_table('eleve')
    op.drop_index(op.f('ix_contact_phonenumber2'), table_name='contact')
    op.drop_index(op.f('ix_contact_phonenumber1'), table_name='contact')
    op.drop_index(op.f('ix_contact_name'), table_name='contact')
    op.drop_index(op.f('ix_contact_mail'), table_name='contact')
    op.drop_index(op.f('ix_contact_fonction'), table_name='contact')
    op.drop_index(op.f('ix_contact_firstname'), table_name='contact')
    op.drop_index(op.f('ix_contact_active'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_classe_name'), table_name='classe')
    op.drop_table('classe')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_promotion_name'), table_name='promotion')
    op.drop_table('promotion')
    op.drop_table('professeur')
    op.drop_index(op.f('ix_niveau_name'), table_name='niveau')
    op.drop_table('niveau')
    op.drop_index(op.f('ix_groupe_name'), table_name='groupe')
    op.drop_table('groupe')
    op.drop_index(op.f('ix_entreprise_ville'), table_name='entreprise')
    op.drop_index(op.f('ix_entreprise_phonenumber'), table_name='entreprise')
    op.drop_index(op.f('ix_entreprise_name'), table_name='entreprise')
    op.drop_index(op.f('ix_entreprise_mail'), table_name='entreprise')
    op.drop_index(op.f('ix_entreprise_adresse2'), table_name='entreprise')
    op.drop_index(op.f('ix_entreprise_adresse1'), table_name='entreprise')
    op.drop_index(op.f('ix_entreprise_active'), table_name='entreprise')
    op.drop_index(op.f('ix_entreprise_CP'), table_name='entreprise')
    op.drop_table('entreprise')
    op.drop_index(op.f('ix_date_annee_scolaire'), table_name='date')
    op.drop_table('date')
    op.drop_index(op.f('ix_annee_scolaire_name'), table_name='annee_scolaire')
    op.drop_table('annee_scolaire')
    # ### end Alembic commands ###
